# Copyright (c) 2023 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - id: nsv
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.gitCommit={{.Commit}}
      - -X main.gitBranch=main
      - -X main.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

archives:
  - id: nsv-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - nsv
    rlcp: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "^ci"
  groups:
    - title: "Dependency Updates"
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 30
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 40
    - title: "Other Work"
      order: 99

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
    - 'sign'
    - '${artifact}@${digest}'
    - --yes

dockers:
  - image_templates:
      - 'purpleclay/nsv:{{ .Tag }}-amd64'
      - 'ghcr.io/purpleclay/nsv:{{ .Tag }}-amd64'
      - 'registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.description=A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/entrypoint.sh
  - image_templates:
      - 'purpleclay/nsv:{{ .Tag }}-arm64'
      - 'ghcr.io/purpleclay/nsv:{{ .Tag }}-arm64'
      - 'registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-arm64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.description=A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - scripts/entrypoint.sh

docker_manifests:
  - name_template: "purpleclay/nsv:{{ .Tag }}"
    image_templates:
      - "purpleclay/nsv:{{ .Tag }}-amd64"
      - "purpleclay/nsv:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/purpleclay/nsv:{{ .Tag }}"
    image_templates:
      - "ghcr.io/purpleclay/nsv:{{ .Tag }}-amd64"
      - "ghcr.io/purpleclay/nsv:{{ .Tag }}-arm64"
  - name_template: "registry.gitlab.com/purpleclay/nsv:{{ .Tag }}"
    image_templates:
      - "registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-amd64"
      - "registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-arm64"
  - name_template: "purpleclay/nsv:latest"
    image_templates:
      - "purpleclay/nsv:{{ .Tag }}-amd64"
      - "purpleclay/nsv:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/purpleclay/nsv:latest"
    image_templates:
      - "ghcr.io/purpleclay/nsv:{{ .Tag }}-amd64"
      - "ghcr.io/purpleclay/nsv:{{ .Tag }}-arm64"
  - name_template: "registry.gitlab.com/purpleclay/nsv:latest"
    image_templates:
      - "registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-amd64"
      - "registry.gitlab.com/purpleclay/nsv:{{ .Tag }}-arm64"

brews:
  - name: nsv
    tap:
      owner: purpleclay
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/purpleclay/nsv"
    description: "A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!"
    license: MIT
    install: |
      bin.install "nsv"

      bash_output = Utils.safe_popen_read(bin/"nsv", "completion", "bash")
      (bash_completion/"nsv").write bash_output

      zsh_output = Utils.safe_popen_read(bin/"nsv", "completion", "zsh")
      (zsh_completion/"_nsv").write zsh_output

      fish_output = Utils.safe_popen_read(bin/"nsv", "completion", "fish")
      (fish_completion/"nsv.fish").write fish_output

      man1.install "manpages/nsv.1.gz"
    test: |
      installed_version = shell_output("#{bin}/nsv version --short 2>&1")
      assert_match "v#{version}", installed_version

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: "https://github.com/purpleclay/nsv"
    description: "A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!"
    maintainer: Purple Clay <purpleclaygh@gmail.com>
    license: MIT
    vendor: Purple Clay
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/nsv.bash
        dst: /usr/share/bash-completion/completions/nsv
        file_info:
          mode: 0644
      - src: ./completions/nsv.fish
        dst: /usr/share/fish/completions/nsv.fish
        file_info:
          mode: 0644
      - src: ./completions/nsv.zsh
        dst: /usr/share/zsh/vendor-completions/_nsv
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/nsv/copyright
        file_info:
          mode: 0644
      - src: ./manpages/nsv.1.gz
        dst: /usr/share/man/man1/nsv.1.gz
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

release:
  footer: |
    **Full Changelog**: https://github.com/purpleclay/nsv/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Follow me on [Twitter](https://twitter.com/purpleclaydev)
    - Follow me on [Fosstodon](https://fosstodon.org/@purpleclaydev)
