site_name: NSV
site_description: Manage your semantic versioning without any config
copyright: Building tools to make developers' lives easier
repo_name: purpleclay/nsv
repo_url: https://github.com/purpleclay/nsv
# Only set during a release to ensure htmltest doesn't break due to non existent directories
site_url: ""
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  logo: static/logo.png
  favicon: static/favicon.ico
  palette:
    primary: deep purple
    accent: purple
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
      - Next Version: next-version.md
      - Semantic Commands: commands.md
      - Playground: playground.md
      - Installation:
          - Binary: install/binary.md
          - From Source: install/source.md
      - Other Bits:
          - License: license.md
  - Reference:
      - Environment Variables: reference/env-vars.md
      - Version Templating: reference/templating.md
      - CLI:
          - nsv: reference/cli/nsv.md
          - nsv next: reference/cli/nsv-next.md
          - nsv playground: reference/cli/nsv-playground.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purpleclay
      name: Purple Clay on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purpleclaydev
      name: Purple Clay on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@purpleclaydev
      name: Purple Clay on Fosstodon
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/purpleclay
      name: Purple Clay on Docker Hub
  status:
    new: New Features Added
    deprecated: No Longer Supported

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: purpleclay/gitz
      branch: main
  - minify:
      minify_html: true
  - search
  - social
  - typeset

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - md_in_html
  - meta
  - toc:
      permalink: true
