name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - purpleclay
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please be as descriptive and concise as possible. We value all input from the community.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what happened.
      placeholder: Tell us what happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce it
      description: Please list all of the steps taken to reproduce this bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version?
      description: Which version of nsv are you using?
      placeholder: nsv version
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) are you using?
      multiple: true
      options:
        - Linux
        - Mac
        - Windows
        - All
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/purpleclay/nsv/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
