name: nix-patch
on:
  # push:
  #   tags:
  #     - "v*.*.*"
  pull_request:

jobs:
  nix-patch:
    runs-on: ubuntu-24.04
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch Version
        run: |
          sed -i 's/version = "[^"]*";/version = "0.10.2";/' default.nix

      # HACK:
      # The most reliable way to calculate the hash for fetchFromGitHub, is to allow nix
      # build to calculate it for us. Comment out the existing hash and run nix build,
      # grep the new hash from the output
      - name: Patch Hash
        run: |
          sed -i 's/hash =/# hash =/' default.nix
          set +e
          nix build 2> error.log
          set -e

          HASH=$(grep -oP 'got:\s+(sha256-\S+)' error.log | awk '{print $2}')
          sed -i "s/# hash = \"[^\"]*\";/hash = \"$HASH\";/" default.nix
        shell: bash

      # HACK:
      # Since the hash has now been set. Run nix-build to generate the new vendorHash
      - name: Patch VendorHash
        run: |
          set +e
          nix build 2> error.log
          set -e

          HASH=$(grep -oP 'got:\s+(sha256-\S+)' error.log | awk '{print $2}')
          sed -i "s/vendorHash = \"[^\"]*\";/vendorHash = \"$HASH\";/" default.nix

      - name: Print
        run: cat default.nix
