name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Download Syft
        uses: anchore/sbom-action/download-syft@v0

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GH_DOCKER_USERNAME }}
          password: ${{ secrets.GH_DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER }}
          FURY_TOKEN: ${{ secrets.GH_FURY_TOKEN }}
