name: shellcheck
on:
  push:
    branches:
      - main
    paths:
      - "scripts/*.sh"
  pull_request:
    branches:
      - main
    paths:
      - "scripts/*.sh"

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    name: shellcheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: ShellCheck
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/shellcheck@v0.3.0
          args: check --src scripts
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
