name: shellcheck
on:
  push:
    branches:
      - main
    paths:
      - "scripts/**"
  pull_request:
    branches:
      - main
    paths:
      - "scripts/**"

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    name: shellcheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"

      - name: ShellCheck
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/shellcheck@v0.1.0
          args: check --src . --paths scripts/*
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
